INSERT INTO teams(wyId, name, city, officialName) VALUES
('1613', 'Newcastle United', 'Newcastle upon Tyne', 'Newcastle United FC'),
('1673', 'Huddersfield Town', 'Huddersfield, West Yorkshire', 'Huddersfield Town FC'),
('10531', 'Swansea City', 'Swansea', 'Swansea City AFC'),
('1659', 'AFC Bournemouth', 'Bournemouth, Dorset', 'AFC Bournemouth'),
('1651', 'Brighton & Hove Albion', 'Brighton, East Sussex', 'Brighton & Hove Albion FC'),
('1646', 'Burnley', 'Burnley, Lancashire', 'Burnley FC'),
('1631', 'Leicester City', 'Leicester', 'Leicester City FC'),
('1633', 'West Ham United', 'London', 'West Ham United FC'),
('1639', 'Stoke City', 'Stoke-on-Trent', 'Stoke City FC'),
('1644', 'Watford', 'Watford', 'Watford FC'),
('1623', 'Everton', 'Liverpool', 'Everton FC'),
('1627', 'West Bromwich Albion', 'West Bromwich', 'West Bromwich Albion FC'),
('1625', 'Manchester City', 'Manchester', 'Manchester City FC'),
('1624', 'Tottenham Hotspur', 'London', 'Tottenham Hotspur FC'),
('1628', 'Crystal Palace', 'London', 'Crystal Palace FC'),
('1619', 'Southampton', 'Southampton, Hampshire', 'Southampton FC'),
('1612', 'Liverpool', 'Liverpool', 'Liverpool FC'),
('1610', 'Chelsea', 'London', 'Chelsea FC'),
('1611', 'Manchester United', 'Manchester', 'Manchester United FC'),
('1609', 'Arsenal', 'London', 'Arsenal FC'),
('1000', 'Aston Villa', 'London', 'N/S'),
('1001', 'Brentford', 'London', 'N/S'),
('1002', 'Wolverhampton Wanderers', 'London', 'N/S'),
('1003', 'Norwich City', 'London', 'N/S'),
('1004', 'Leeds United', 'London', 'N/S');
