INSERT INTO area(alpha2code, alpha3code, name) VALUES
('TR', 'TUR', 'Turkey'),
('SN', 'SEN', 'Senegal'),
('FR', 'FRA', 'France'),
('NL', 'NLD', 'Netherlands'),
('BE', 'BEL', 'Belgium'),
('DK', 'DNK', 'Denmark'),
('AT', 'AUT', 'Austria'),
('IS', 'ISL', 'Iceland'),
('FI', 'FIN', 'Finland'),
('CW', 'CUW', 'Curaçao'),
('PL', 'POL', 'Poland'),
('BR', 'BRA', 'Brazil'),
('IQ', 'IRQ', 'Iraq'),
('GH', 'GHA', 'Ghana'),
('SE', 'SWE', 'Sweden'),
('MA', 'MAR', 'Morocco'),
('RS', 'SRB', 'Serbia'),
('SK', 'SVK', 'Slovakia'),
('CI', 'CIV', 'Côte dIvoire'),
('VE', 'VEN', 'Venezuela'),
('IT', 'ITA', 'Italy'),
('NG', 'NGA', 'Nigeria'),
('KR', 'KOR', 'Korea Republic'),
('GM', 'GMB', 'Gambia'),
('RO', 'ROU', 'Romania'),
('CH', 'CHE', 'Switzerland'),
('CD', 'COD', 'Congo DR'),
('DZ', 'DZA', 'Algeria'),
('AR', 'ARG', 'Argentina'),
('JP', 'JPN', 'Japan'),
('CG', 'COG', 'Congo'),
('ES', 'ESP', 'Spain'),
('RU', 'RUS', 'Russia'),
('BF', 'BFA', 'Burkina Faso'),
('HR', 'HRV', 'Croatia'),
('LT', 'LTU', 'Lithuania'),
('DE', 'DEU', 'Germany'),
('ML', 'MLI', 'Mali'),
('UY', 'URY', 'Uruguay'),
('AF', 'AFG', 'Afghanistan'),
('EG', 'EGY', 'Egypt'),
('MR', 'MRT', 'Mauritania'),
('NC', 'NCL', 'New Caledonia'),
('AL', 'ALB', 'Albania'),
('PE', 'PER', 'Peru'),
('CZ', 'CZE', 'Czech Republic'),
('PY', 'PRY', 'Paraguay'),
('PT', 'PRT', 'Portugal'),
('MQ', 'MTQ', 'Martinique'),
('TN', 'TUN', 'Tunisia'),
('AO', 'AGO', 'Angola'),
('CO', 'COL', 'Colombia'),
('CR', 'CRI', 'Costa Rica'),
('IR', 'IRN', 'Iran'),
('CV', 'CPV', 'Cape Verde Islands'),
('KE', 'KEN', 'Kenya'),
('MX', 'MEX', 'Mexico'),
('CL', 'CHL', 'Chile'),
('TD', 'TCD', 'Chad'),
('DO', 'DOM', 'Dominican Republic'),
('CN', 'CHN', 'China PR'),
('GR', 'GRC', 'Greece'),
('HU', 'HUN', 'Hungary'),
('SI', 'SVN', 'Slovenia'),
('BA', 'BIH', 'Bosnia-Herzegovina'),
('HN', 'HND', 'Honduras'),
('MZ', 'MOZ', 'Mozambique'),
('TG', 'TGO', 'Togo'),
('CM', 'CMR', 'Cameroon'),
('ZA', 'ZAF', 'South Africa'),
('JM', 'JAM', 'Jamaica'),
('BI', 'BDI', 'Burundi'),
('ER', 'ERI', 'Eritrea'),
('GN', 'GIN', 'Guinea'),
('UA', 'UKR', 'Ukraine'),
('RE', 'REU', 'Reunion'),
('ME', 'MNE', 'Montenegro'),
('SR', 'SUR', 'Suriname'),
('GY', 'GUY', 'Guyana'),
('BJ', 'BEN', 'Benin'),
('IE', 'IRL', 'Ireland Republic'),
('MK', 'MKD', 'Macedonia FYR'),
('LY', 'LBY', 'Libya'),
('KP', 'PRK', 'Korea DPR'),
('KM', 'COM', 'Comoros'),
('NO', 'NOR', 'Norway'),
('NE', 'NER', 'Niger'),
('GF', 'GUF', 'French Guiana'),
('US', 'USA', 'United States'),
('GA', 'GAB', 'Gabon'),
('LU', 'LUX', 'Luxembourg'),
('GP', 'GLP', 'Guadeloupe'),
('SL', 'SLE', 'Sierra Leone'),
('AU', 'AUS', 'Australia'),
('ET', 'ETH', 'Ethiopia'),
('HT', 'HTI', 'Haiti'),
('MU', 'MUS', 'Mauritius'),
('CF', 'CAF', 'Central African Republic'),
('PA', 'PAN', 'Panama'),
('BG', 'BGR', 'Bulgaria'),
('CA', 'CAN', 'Canada'),
('ID', 'IDN', 'Indonesia'),
('TT', 'TTO', 'Trinidad and Tobago'),
('LI', 'LIE', 'Liechtenstein'),
('TZ', 'TZA', 'Tanzania'),
('SA', 'SAU', 'Saudi Arabia'),
('TJ', 'TJK', 'Tajikistan'),
('GW', 'GNB', 'Guinea-Bissau'),
('PH', 'PHL', 'Philippines'),
('RW', 'RWA', 'Rwanda'),
('LA', 'LAO', 'Laos'),
('KZ', 'KAZ', 'Kazakhstan'),
('SD', 'SDN', 'Sudan'),
('LB', 'LBN', 'Lebanon'),
('WS', 'WSM', 'Samoa'),
('ST', 'STP', 'São Tomé e Príncipe'),
('CU', 'CUB', 'Cuba'),
('GQ', 'GNQ', 'Equatorial Guinea'),
('EC', 'ECU', 'Ecuador'),
('EE', 'EST', 'Estonia'),
('LC', 'LCA', 'St. Lucia'),
('LV', 'LVA', 'Latvia'),
('AM', 'ARM', 'Armenia'),
('IL', 'ISR', 'Israel'),
('GD', 'GRD', 'Grenada'),
('NZ', 'NZL', 'New Zealand'),
('BM', 'BMU', 'Bermuda'),
('ZM', 'ZMB', 'Zambia'),
('BB', 'BRB', 'Barbados'),
('MS', 'MSR', 'Montserrat'),
('ZW', 'ZWE', 'Zimbabwe'),
('BD', 'BGD', 'Bangladesh');
