INSERT INTO subevents(subEventId, subEventName) VALUES
(85, 'Simple pass'),
(83, 'High pass'),
(82, 'Head pass'),
(10, 'Air duel'),
(13, 'Ground loose ball duel'),
(86, 'Smart pass'),
(84, 'Launch'),
(12, 'Ground defending duel'),
(11, 'Ground attacking duel'),
(20, 'Foul'),
(31, 'Free Kick'),
(80, 'Cross'),
(100, 'Shot'),
(90, 'Reflexes'),
(72, 'Touch'),
(71, 'Clearance'),
(50, 'Ball out of the field'),
(36, 'Throw in'),
(34, 'Goal kick'),
(30, 'Corner'),
(40, 'Goalkeeper leaving line'),
(81, 'Hand pass'),
(70, 'Acceleration'),
(91, 'Save attempt'),
(32, 'Free kick cross'),
(33, 'Free kick shot'),
(21, 'Hand foul'),
(27, 'Violent Foul'),
(24, 'Protest'),
(51, 'Whistle'),
(22, 'Late card foul'),
(23, 'Out of game foul'),
(35, 'Penalty'),
(26, 'Time lost foul'),
(25, 'Simulation');
